name: data-science-environment
dependencies:
  - ipykernel
  - jupyter
  - keras
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pymc3
  - python=3.7
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow
